volumes:
  postgres:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: profile
      POSTGRES_PASSWORD: profile
      POSTGRES_DB: profile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports: 
      - 5432:5432

  server:
    build: .
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
      
