volumes:
  go-mod:
  go-build:

services:
  profile:
    build:
      target: builder
    volumes:
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build

      - $PWD:$PWD
    working_dir: $PWD
    entrypoint: [ go, run, ./cmd ]

  genx509:
    image: jitesoft/step-cli
    volumes:
      - $PWD:$PWD
    working_dir: $PWD/.local
    entrypoint: [sh, -c]
    command:
      - |-
        set -e
        step certificate create ca ca.crt ca.key --profile root-ca --no-password --insecure -f
        step certificate create profile profile.crt profile.key --san localhost --profile leaf --ca ca.crt --ca-key ca.key --no-password --insecure -f
        step certificate create tenant tenant.crt tenant.key --san localhost --profile leaf --ca ca.crt --ca-key ca.key --no-password --insecure -f
      