volumes:
  postgres:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: testing
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports: 
      - 5432:5432

  profile:
    build: .
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    environment:
      PROFILE_HTTP_LISTEN_ADDRESS: :8443
      PROFILE_HTTP_TLS_KEY_PATH: /local/localhost.key
      PROFILE_HTTP_TLS_CERT_PATH: /local/localhost.crt
      PROFILE_HTTP_CA_CERTS_PATHS: /local/ca.crt
      PROFILE_HTTP_MTLS: "false"

      PROFILE_TENANT_SERVICE_BASE_URL: https://tenant:8443

      PROFILE_POSTGRES_URL: postgres://testing:testing@postgres:5432/testing?sslmode=disable
      PROFILE_POSTGRES_AEAD_KEY_PATH: /local/tink-aead.json
      PROFILE_POSTGRES_MAC_KEY_PATH: /local/tink-mac.json
    volumes:
      - ./.local:/local
    ports:
      - 8443:8443
      

  tenant:
    image: caddy:2.7.6
    restart: unless-stopped
    volumes:
      - ./.local:/local
    entrypoint:
      - sh 
      - -c 
      - |
        caddy run -a caddyfile -c - <<-'EOF'
        :8443 {
          tls /local/tenant.crt /local/tenant.key {
            ca_root /local/ca.crt
            client_auth {
              mode require_and_verify
              trusted_ca_cert_file /local/ca.crt
            }
          }

          header Content-Type application/json
          respond /tenants/018e282f-0a88-7950-91d8-34cb8f9a9c2c 200 {
            body <<JSON
              {"id":"018e282f-0a88-7950-91d8-34cb8f9a9c2c","name":"dummy","expire":"2034-12-31T23:59:59.99999+07:00"}
            JSON
          }
        }
        EOF